/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Document {
  'service' : [] | [ExternalBlob],
  'registration' : [] | [ExternalBlob],
  'insurance' : [] | [ExternalBlob],
  'pollution' : [] | [ExternalBlob],
}
export interface Expiry {
  'service' : Time,
  'roadTax' : Time,
  'insurance' : Time,
  'pollution' : Time,
}
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export type Type = { 'bus' : null } |
  { 'car' : null } |
  { 'truck' : null } |
  { 'other' : null } |
  { 'bike' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'expiryDates' : Expiry,
  'model' : string,
  'vehicleType' : Type,
  'documents' : Document,
  'owner' : Principal,
  'registration' : string,
  'name' : string,
}
export interface VehicleInput {
  'expiryDates' : Expiry,
  'model' : string,
  'vehicleType' : Type,
  'registration' : string,
  'name' : string,
}
export interface VehicleUpdate {
  'expiryDates' : [] | [Expiry],
  'model' : [] | [string],
  'vehicleType' : [] | [Type],
  'registration' : [] | [string],
  'name' : [] | [string],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVehicle' : ActorMethod<[VehicleInput], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteVehicle' : ActorMethod<[string], undefined>,
  'getAllVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getAllVehiclesByOwner' : ActorMethod<[Principal], Array<Vehicle>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpiringIn' : ActorMethod<[bigint], Array<Vehicle>>,
  'getVehicle' : ActorMethod<[string], Vehicle>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateVehicle' : ActorMethod<[string, VehicleUpdate], undefined>,
  'updateVehicleDocuments' : ActorMethod<[string, Document], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];