/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Expiry = IDL.Record({
  'service' : Time,
  'roadTax' : Time,
  'insurance' : Time,
  'pollution' : Time,
});
export const Type = IDL.Variant({
  'bus' : IDL.Null,
  'car' : IDL.Null,
  'truck' : IDL.Null,
  'other' : IDL.Null,
  'bike' : IDL.Null,
});
export const VehicleInput = IDL.Record({
  'expiryDates' : Expiry,
  'model' : IDL.Text,
  'vehicleType' : Type,
  'registration' : IDL.Text,
  'name' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Document = IDL.Record({
  'service' : IDL.Opt(ExternalBlob),
  'registration' : IDL.Opt(ExternalBlob),
  'insurance' : IDL.Opt(ExternalBlob),
  'pollution' : IDL.Opt(ExternalBlob),
});
export const Vehicle = IDL.Record({
  'expiryDates' : Expiry,
  'model' : IDL.Text,
  'vehicleType' : Type,
  'documents' : Document,
  'owner' : IDL.Principal,
  'registration' : IDL.Text,
  'name' : IDL.Text,
});
export const VehicleUpdate = IDL.Record({
  'expiryDates' : IDL.Opt(Expiry),
  'model' : IDL.Opt(IDL.Text),
  'vehicleType' : IDL.Opt(Type),
  'registration' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVehicle' : IDL.Func([VehicleInput], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteVehicle' : IDL.Func([IDL.Text], [], []),
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getAllVehiclesByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Vehicle)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpiringIn' : IDL.Func([IDL.Int], [IDL.Vec(Vehicle)], ['query']),
  'getVehicle' : IDL.Func([IDL.Text], [Vehicle], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateVehicle' : IDL.Func([IDL.Text, VehicleUpdate], [], []),
  'updateVehicleDocuments' : IDL.Func([IDL.Text, Document], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Expiry = IDL.Record({
    'service' : Time,
    'roadTax' : Time,
    'insurance' : Time,
    'pollution' : Time,
  });
  const Type = IDL.Variant({
    'bus' : IDL.Null,
    'car' : IDL.Null,
    'truck' : IDL.Null,
    'other' : IDL.Null,
    'bike' : IDL.Null,
  });
  const VehicleInput = IDL.Record({
    'expiryDates' : Expiry,
    'model' : IDL.Text,
    'vehicleType' : Type,
    'registration' : IDL.Text,
    'name' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Document = IDL.Record({
    'service' : IDL.Opt(ExternalBlob),
    'registration' : IDL.Opt(ExternalBlob),
    'insurance' : IDL.Opt(ExternalBlob),
    'pollution' : IDL.Opt(ExternalBlob),
  });
  const Vehicle = IDL.Record({
    'expiryDates' : Expiry,
    'model' : IDL.Text,
    'vehicleType' : Type,
    'documents' : Document,
    'owner' : IDL.Principal,
    'registration' : IDL.Text,
    'name' : IDL.Text,
  });
  const VehicleUpdate = IDL.Record({
    'expiryDates' : IDL.Opt(Expiry),
    'model' : IDL.Opt(IDL.Text),
    'vehicleType' : IDL.Opt(Type),
    'registration' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVehicle' : IDL.Func([VehicleInput], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteVehicle' : IDL.Func([IDL.Text], [], []),
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getAllVehiclesByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Vehicle)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpiringIn' : IDL.Func([IDL.Int], [IDL.Vec(Vehicle)], ['query']),
    'getVehicle' : IDL.Func([IDL.Text], [Vehicle], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateVehicle' : IDL.Func([IDL.Text, VehicleUpdate], [], []),
    'updateVehicleDocuments' : IDL.Func([IDL.Text, Document], [], []),
  });
};

export const init = ({ IDL }) => { return []; };